const ONE_MINUTE = 60;
const ONE_HOUR = 60 * ONE_MINUTE;
const ONE_DAY = 24 * ONE_HOUR;

export const INTERVALS = [
  2 * ONE_MINUTE,
  5 * ONE_MINUTE,
  10 * ONE_MINUTE,
  15 * ONE_MINUTE,
  30 * ONE_MINUTE,
  ONE_HOUR,
  4 * ONE_HOUR,
  12 * ONE_HOUR,
  ONE_DAY,
  3 * ONE_DAY,
  7 * ONE_DAY,
  14 * ONE_DAY,
  30 * ONE_DAY,
];
